### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by grauschnabel** [steckerhalter/org-mobile-sync#3]
hi there,

should this work also if I have
`(setq org-mobile-directory "/mydomain.at:mobileorg")
`
for using mobileorg over ssh ?
It tells me:
`tramp-file-name-handler: No file notification program found on /scp:mydomain.at:
`
am I missinng dependencies?

Thanks

**Comment by steckerhalter** [comment]
Hi, I think this won't work. File change notifications (inotify) only work locally. So Emacs gets information that a certain file has changed from the system. But for remote systems this doesn't work: http://unix.stackexchange.com/questions/144486/how-do-i-use-inotify-or-named-pipes-over-sshfs

**Comment by grauschnabel** [comment]
Thanks, I thought so.
